
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Complaint, ComplaintAttachment } from '@/types';
import { ComplaintCategory, ComplaintStatus } from "@/types";
import { useAuth } from "@/hooks/use-auth";
import { UploadCloud } from "lucide-react";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";

const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
const ALLOWED_FILE_TYPES = ["image/jpeg", "image/png", "image/gif", "application/pdf", "text/plain"];

const formSchema = z.object({
  category: z.nativeEnum(ComplaintCategory, {
    required_error: "Please select a category.",
  }),
  description: z.string().min(10, {
    message: "Description must be at least 10 characters.",
  }).max(2000, { message: "Description must not exceed 2000 characters."}),
  attachments: z
    .custom<FileList>((val) => val instanceof FileList, "Please upload a file list")
    .optional()
    .refine(
      (files) => !files || Array.from(files).every((file) => file.size <= MAX_FILE_SIZE),
      `Max file size is 5MB.`
    )
    .refine(
      (files) => !files || Array.from(files).every((file) => ALLOWED_FILE_TYPES.includes(file.type)),
      "Only .jpg, .jpeg, .png, .gif, .pdf, .txt files are allowed."
    ),
});

interface SubmitComplaintFormProps {
  onComplaintSubmitted: (complaint: Complaint) => void; // Callback with the newly created complaint from API
}

const readFileAsDataURL = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        console.log(`[readFileAsDataURL] FileReader result (first 100 chars): ${reader.result.substring(0, 100)}`);
        console.log(`[readFileAsDataURL] FileReader result length: ${reader.result.length}`);
        resolve(reader.result);
      } else {
        console.error('[readFileAsDataURL] FileReader result was not a string.');
        reject(new Error('FileReader did not return a string.'));
      }
    };
    reader.onerror = (error) => {
      console.error('[readFileAsDataURL] FileReader error:', error);
      reject(error);
    };
    reader.readAsDataURL(file);
  });
};

export function SubmitComplaintForm({ onComplaintSubmitted }: SubmitComplaintFormProps) {
  const { user } = useAuth();
  const { toast } = useToast();
  const [fileNames, setFileNames] = useState<string[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      description: "",
    },
  });

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      form.setValue("attachments", files);
      setFileNames(Array.from(files).map(file => file.name));
    } else {
      form.setValue("attachments", undefined);
      setFileNames([]);
    }
  };

  async function onSubmit(values: z.infer<typeof formSchema>) {
    if (!user) {
      toast({ title: "Authentication Error", description: "You must be logged in to submit a complaint.", variant: "destructive" });
      return;
    }
    setIsSubmitting(true);

    const processedAttachments: Omit<ComplaintAttachment, 'id'>[] = [];
    if (values.attachments && values.attachments.length > 0) {
      for (const file of Array.from(values.attachments)) {
        try {
          const dataUrl = await readFileAsDataURL(file);
          console.log(`[SubmitComplaintForm] Processed file ${file.name}, Data URI Length: ${dataUrl?.length}`);
          processedAttachments.push({
            fileName: file.name,
            fileType: file.type,
            url: dataUrl,
            // id will be generated by MongoDB for subdocuments
          });
        } catch (error) {
          console.error("Error reading file for submission:", file.name, error);
          toast({ title: "File Error", description: `Could not process file: ${file.name}`, variant: "destructive" });
        }
      }
    }

    const newComplaintData = {
      customerId: user.id, // This is now MongoDB _id string
      customerName: user.name,
      category: values.category,
      description: values.description,
      status: ComplaintStatus.Submitted,
      attachments: processedAttachments,
      // submittedAt and updatedAt will be set by the server/DB
    };
    console.log("[SubmitComplaintForm] Submitting complaint data to API:", newComplaintData);

    try {
      const response = await fetch('/api/complaints', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newComplaintData),
      });

      if (response.ok) {
        const createdComplaint: Complaint = await response.json();
        toast({ title: "Complaint Submitted", description: `Your complaint #${createdComplaint.id.slice(-6)} has been submitted.` });
        onComplaintSubmitted(createdComplaint); // Pass the complaint received from API
        form.reset();
        setFileNames([]);
      } else {
        const errorData = await response.json();
        toast({ title: "Submission Failed", description: errorData.message || "Could not submit your complaint.", variant: "destructive" });
      }
    } catch (error) {
      console.error("Error submitting complaint via API:", error);
      toast({ title: "Network Error", description: "Failed to connect to the server.", variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Card className="shadow-md">
      <CardHeader>
        <CardTitle>Submit New Complaint</CardTitle>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="category"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Category</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select a complaint category" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {Object.values(ComplaintCategory).map(cat => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Describe your issue in detail..."
                      className="min-h-[120px]"
                      {...field}
                    />
                  </FormControl>
                  <FormDescription>
                    Please include all relevant details, like dates, times, product names, or people involved.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="attachments"
              render={() => ( // field is not directly used as Input type="file" is handled differently
                <FormItem>
                  <FormLabel>Supporting Documents/Images (Optional)</FormLabel>
                  <FormControl>
                    <div className="flex items-center justify-center w-full">
                        <label htmlFor="dropzone-file" className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-lg cursor-pointer bg-secondary hover:bg-muted border-input">
                            <div className="flex flex-col items-center justify-center pt-5 pb-6">
                                <UploadCloud className="w-8 h-8 mb-2 text-muted-foreground" />
                                {fileNames.length > 0 ? (
                                  <div className="text-sm text-foreground text-center">
                                    <p className="font-semibold">Selected:</p>
                                    {fileNames.map((name, idx) => <p key={idx} className="text-xs truncate max-w-xs">{name}</p>)}
                                  </div>
                                ) : (
                                  <>
                                    <p className="mb-1 text-sm text-muted-foreground"><span className="font-semibold">Click to upload</span> or drag and drop</p>
                                    <p className="text-xs text-muted-foreground">Images, PDF, TXT (MAX. 5MB per file)</p>
                                  </>
                                )}
                            </div>
                            <Input 
                              id="dropzone-file" 
                              type="file" 
                              className="hidden" 
                              onChange={handleFileChange} 
                              multiple
                              accept={ALLOWED_FILE_TYPES.join(",")}
                            />
                        </label>
                    </div> 
                  </FormControl>
                   <FormDescription>
                    IMPORTANT: For production apps, consider dedicated file storage (e.g., S3, Firebase Storage) instead of embedding large files in the database.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
             <Button type="submit" className="w-full sm:w-auto" disabled={isSubmitting}>
                {isSubmitting ? "Submitting..." : "Submit Complaint"}
             </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
